/*
  ============================================================================
  CLOUD warehouse — cleanup Detail hard-delete sync ghosts (last 2 days)
  ============================================================================
  Scope: yesterday + today (UTC), all *Detail tables.

  Does:
    1) Hard-DELETE IsDeleted=1 ghosts (last 2 days)
    2) Hard-DELETE rows whose IDs appear in Cloud C2L Op=D outbox (last 2 days)
       — covers soft-apply that left IsDeleted=0 wrongly or failed hard-delete
    3) Requeue C2L Op=D
    4) Ensure SyncApply_PurchaseDetail / TransferDetail / SaleDetail have @Operation

  Also paste SqlBatch generated by LOCAL Cleanup_DetailDeleteGhosts_2Days_LOCAL.sql
  (section 3) into this session if Local→Cloud orphans remain.
*/

SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

PRINT N'============================================================';
PRINT N'CLOUD Detail-delete cleanup (last 2 days)';
PRINT N'DB=' + DB_NAME() + N'  Utc=' + CONVERT(nvarchar(30), SYSUTCDATETIME(), 126);
PRINT N'============================================================';

IF DB_NAME() IN (N'SB1', N'SB')
BEGIN
    RAISERROR(N'STOP: This is LOCAL. Use Cleanup_DetailDeleteGhosts_2Days_LOCAL.sql', 16, 1);
    RETURN;
END
GO

DECLARE @since datetime2(3) = DATEADD(day, -2, SYSUTCDATETIME());
PRINT N'Window since (UTC): ' + CONVERT(nvarchar(30), @since, 126);
GO

/* ---------- 0) Apply markers ---------- */
PRINT N'--- 0) SyncApply markers ---';
SELECT
  CASE WHEN OBJECT_ID(N'dbo.SyncApply_Generic', N'P') IS NULL THEN N'MISSING'
       WHEN OBJECT_DEFINITION(OBJECT_ID(N'dbo.SyncApply_Generic')) LIKE N'%hardDeleteDetail%'
            THEN N'OK_hardDeleteDetail'
       ELSE N'BAD_run_DataSync_10' END AS ApplyVer;
GO

/* ---------- 1) IsDeleted=1 ghosts ---------- */
PRINT N'--- 1) Hard-delete IsDeleted=1 *Detail ghosts (last 2 days) ---';

DECLARE @since datetime2(3) = DATEADD(day, -2, SYSUTCDATETIME());
DECLARE @tbl sysname, @sql nvarchar(max), @cnt int, @modCol sysname;

DECLARE dcur CURSOR LOCAL FAST_FORWARD FOR
SELECT t.name
FROM sys.tables t
INNER JOIN sys.schemas s ON s.schema_id = t.schema_id AND s.name = N'dbo'
WHERE t.name LIKE N'%Detail'
  AND t.name NOT LIKE N'%History%'
ORDER BY t.name;

OPEN dcur;
FETCH NEXT FROM dcur INTO @tbl;
WHILE @@FETCH_STATUS = 0
BEGIN
    IF COL_LENGTH(N'dbo.' + @tbl, N'IsDeleted') IS NULL
    BEGIN
        PRINT N'  ' + @tbl + N': no IsDeleted — skip';
        FETCH NEXT FROM dcur INTO @tbl;
        CONTINUE;
    END

    SET @modCol = CASE
        WHEN COL_LENGTH(N'dbo.' + @tbl, N'SyncModifiedAt') IS NOT NULL THEN N'SyncModifiedAt'
        WHEN COL_LENGTH(N'dbo.' + @tbl, N'SyncModifiedAt') IS NOT NULL THEN N'SyncModifiedAt'
        WHEN COL_LENGTH(N'dbo.' + @tbl, N'DeletedAt') IS NOT NULL THEN N'DeletedAt'
        ELSE NULL END;

    SET @sql = N'SELECT @c = COUNT(*) FROM dbo.' + QUOTENAME(@tbl)
             + N' WHERE ISNULL(IsDeleted,0)=1';
    IF @modCol IS NOT NULL
        SET @sql += N' AND ' + QUOTENAME(@modCol) + N' >= @since';

    BEGIN TRY
        EXEC sp_executesql @sql, N'@c int OUTPUT, @since datetime2(3)', @c=@cnt OUTPUT, @since=@since;
        IF @cnt > 0
        BEGIN
            BEGIN TRY EXEC sp_set_session_context @key = N'SyncSuppressOutbox', @value = 1; END TRY BEGIN CATCH END CATCH;
            BEGIN TRY EXEC sp_set_session_context @key = N'SyncAllowPhysicalDelete', @value = 1; END TRY BEGIN CATCH END CATCH;

            SET @sql = N'DELETE FROM dbo.' + QUOTENAME(@tbl) + N' WHERE ISNULL(IsDeleted,0)=1';
            IF @modCol IS NOT NULL
                SET @sql += N' AND ' + QUOTENAME(@modCol) + N' >= @since';
            EXEC sp_executesql @sql, N'@since datetime2(3)', @since=@since;
            PRINT N'  ' + @tbl + N' ghosts hard-deleted: ' + CAST(@@ROWCOUNT AS nvarchar(20));

            BEGIN TRY EXEC sp_set_session_context @key = N'SyncSuppressOutbox', @value = NULL; END TRY BEGIN CATCH END CATCH;
            BEGIN TRY EXEC sp_set_session_context @key = N'SyncAllowPhysicalDelete', @value = NULL; END TRY BEGIN CATCH END CATCH;
        END
        ELSE
            PRINT N'  ' + @tbl + N': 0 ghosts';
    END TRY
    BEGIN CATCH
        PRINT N'  ' + @tbl + N' SKIP: ' + ERROR_MESSAGE();
    END CATCH

    FETCH NEXT FROM dcur INTO @tbl;
END
CLOSE dcur; DEALLOCATE dcur;
GO

/* ---------- 2) Hard-delete by Cloud C2L Op=D outbox IDs ---------- */
PRINT N'--- 2) Hard-delete rows referenced by C2L Op=D (last 2 days) ---';

DECLARE @since datetime2(3) = DATEADD(day, -2, SYSUTCDATETIME());
DECLARE @tbl sysname, @sql nvarchar(max), @ids nvarchar(max);

DECLARE tcur CURSOR LOCAL FAST_FORWARD FOR
SELECT DISTINCT TableName
FROM dbo.SyncOutbox
WHERE Direction = N'C2L'
  AND TableName LIKE N'%Detail'
  AND Operation = N'D'
  AND CreatedAt >= @since
  AND OBJECT_ID(N'dbo.' + TableName, N'U') IS NOT NULL;

OPEN tcur;
FETCH NEXT FROM tcur INTO @tbl;
WHILE @@FETCH_STATUS = 0
BEGIN
    SELECT @ids = STRING_AGG(CAST(v.IdVal AS nvarchar(30)), N',')
    FROM (
        SELECT DISTINCT TRY_CAST(JSON_VALUE(PrimaryKeyJson, N'$.ID') AS bigint) AS IdVal
        FROM dbo.SyncOutbox
        WHERE Direction = N'C2L'
          AND TableName = @tbl
          AND Operation = N'D'
          AND CreatedAt >= @since
          AND TRY_CAST(JSON_VALUE(PrimaryKeyJson, N'$.ID') AS bigint) IS NOT NULL
    ) v;

    IF @ids IS NOT NULL AND LEN(@ids) > 0
    BEGIN
        BEGIN TRY
            BEGIN TRY EXEC sp_set_session_context @key = N'SyncSuppressOutbox', @value = 1; END TRY BEGIN CATCH END CATCH;
            BEGIN TRY EXEC sp_set_session_context @key = N'SyncAllowPhysicalDelete', @value = 1; END TRY BEGIN CATCH END CATCH;

            SET @sql = N'DELETE FROM dbo.' + QUOTENAME(@tbl) + N' WHERE ID IN (' + @ids + N')';
            EXEC(@sql);
            PRINT N'  ' + @tbl + N' Op=D IDs removed: ' + CAST(@@ROWCOUNT AS nvarchar(20))
                + N' (IDs: ' + LEFT(@ids, 200) + CASE WHEN LEN(@ids)>200 THEN N'...' ELSE N'' END + N')';

            BEGIN TRY EXEC sp_set_session_context @key = N'SyncSuppressOutbox', @value = NULL; END TRY BEGIN CATCH END CATCH;
            BEGIN TRY EXEC sp_set_session_context @key = N'SyncAllowPhysicalDelete', @value = NULL; END TRY BEGIN CATCH END CATCH;
        END TRY
        BEGIN CATCH
            PRINT N'  ' + @tbl + N' SKIP: ' + ERROR_MESSAGE();
        END CATCH
    END
    ELSE
        PRINT N'  ' + @tbl + N': no parseable Op=D IDs';

    FETCH NEXT FROM tcur INTO @tbl;
END
CLOSE tcur; DEALLOCATE tcur;
GO

/* ---------- 3) Known Purchase/Transfer orphans from recent tickets (safe if already gone) ---------- */
PRINT N'--- 3) Known ticket orphans (no-op if missing) ---';
BEGIN TRY EXEC sp_set_session_context @key = N'SyncSuppressOutbox', @value = 1; END TRY BEGIN CATCH END CATCH;
BEGIN TRY EXEC sp_set_session_context @key = N'SyncAllowPhysicalDelete', @value = 1; END TRY BEGIN CATCH END CATCH;

IF OBJECT_ID(N'dbo.PurchaseDetail', N'U') IS NOT NULL
BEGIN
    DELETE FROM dbo.PurchaseDetail WHERE ID IN (20384, 20385);
    PRINT N'PurchaseDetail 20384/20385: ' + CAST(@@ROWCOUNT AS nvarchar(20));
END

IF OBJECT_ID(N'dbo.TransferDetail', N'U') IS NOT NULL
BEGIN
    DELETE FROM dbo.TransferDetail WHERE ID IN (64191, 64276);
    PRINT N'TransferDetail 64191/64276: ' + CAST(@@ROWCOUNT AS nvarchar(20));
END

BEGIN TRY EXEC sp_set_session_context @key = N'SyncSuppressOutbox', @value = NULL; END TRY BEGIN CATCH END CATCH;
BEGIN TRY EXEC sp_set_session_context @key = N'SyncAllowPhysicalDelete', @value = NULL; END TRY BEGIN CATCH END CATCH;
GO

/* ---------- 4) Wrappers @Operation ---------- */
PRINT N'--- 4) Ensure Detail apply wrappers have @Operation ---';

DECLARE @wrap sysname, @sql nvarchar(max);
DECLARE wcur CURSOR LOCAL FAST_FORWARD FOR
SELECT v.Name FROM (VALUES
    (N'SyncApply_PurchaseDetail'),
    (N'SyncApply_TransferDetail'),
    (N'SyncApply_SaleDetail')
) v(Name);

OPEN wcur;
FETCH NEXT FROM wcur INTO @wrap;
WHILE @@FETCH_STATUS = 0
BEGIN
    IF OBJECT_ID(N'dbo.' + @wrap, N'P') IS NOT NULL
       AND OBJECT_DEFINITION(OBJECT_ID(N'dbo.' + @wrap)) LIKE N'%@Operation%'
        PRINT N'  ' + @wrap + N' OK';
    ELSE IF OBJECT_ID(N'dbo.SyncApply_Generic', N'P') IS NOT NULL
    BEGIN
        IF OBJECT_ID(N'dbo.' + @wrap, N'P') IS NOT NULL
            EXEC(N'DROP PROCEDURE dbo.' + @wrap);

        SET @sql = N'
CREATE PROCEDURE dbo.' + @wrap + N'
    @Source varchar(10),
    @PayloadJson nvarchar(max),
    @RemoteModifiedAt datetime2(3),
    @PrimaryKeyJson nvarchar(500),
    @OutboxID bigint = NULL,
    @Operation char(1) = NULL,
    @ConflictLogged bit OUTPUT,
    @Applied bit OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    EXEC dbo.SyncApply_Generic
        @Source = @Source,
        @TableName = N''' + REPLACE(@wrap, N'SyncApply_', N'') + N''',
        @PayloadJson = @PayloadJson,
        @PrimaryKeyJson = @PrimaryKeyJson,
        @RemoteModifiedAt = @RemoteModifiedAt,
        @Operation = @Operation,
        @OutboxID = @OutboxID,
        @ConflictLogged = @ConflictLogged OUTPUT,
        @Applied = @Applied OUTPUT;
END';
        EXEC(@sql);
        PRINT N'  ' + @wrap + N' created (+@Operation)';
    END
    ELSE
        PRINT N'  ' + @wrap + N' SKIP — SyncApply_Generic missing';

    FETCH NEXT FROM wcur INTO @wrap;
END
CLOSE wcur; DEALLOCATE wcur;
GO

/* ---------- 5) Requeue C2L Op=D ---------- */
PRINT N'--- 5) Requeue C2L *Detail Op=D (last 2 days) ---';
DECLARE @since datetime2(3) = DATEADD(day, -2, SYSUTCDATETIME());

UPDATE dbo.SyncOutbox
SET Status = N'Pending',
    AttemptCount = 0,
    LastError = NULL,
    SyncedAt = NULL,
    SyncModifiedAt = SYSUTCDATETIME()
WHERE Direction = N'C2L'
  AND TableName LIKE N'%Detail'
  AND Operation = N'D'
  AND Status IN (N'Synced', N'Conflict', N'DeadLetter', N'Syncing')
  AND CreatedAt >= @since;
PRINT N'Requeued: ' + CAST(@@ROWCOUNT AS nvarchar(20));
GO

PRINT N'============================================================';
PRINT N'CLOUD DONE.';
PRINT N'If Local still shows orphans on Cloud: paste SqlBatch from';
PRINT N'  Cleanup_DetailDeleteGhosts_2Days_LOCAL.sql section 3';
PRINT N'============================================================';
GO
